version: "3.9"


services:
  db:
    # Definição do banco de dados postrgesql
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:${POSTGRES_PORT}"
      
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
  